name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup conda environment
        run: conda create --quiet --name usrse-map geopy pytest

      - name: Run tests
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate usrse-map
          pytest -v -x tests/test_*.py
